// Code generated by Slice Machine. DO NOT EDIT.

import CustomerReviews from './CustomerReviews/index.svelte';
import Hero from './Hero/index.svelte';
import ImpactNumbers from './ImpactNumbers/index.svelte';
import LogoGrid from './LogoGrid/index.svelte';
import MediaGrid from './MediaGrid/index.svelte';
import MultiBlockTextImage from './MultiBlockTextImage/index.svelte';
import Footer from './Footer/index.svelte';
import HorizontalShowcase from './HorizontalShowcase/index.svelte';
import ImageText from './ImageText/index.svelte';
import TeamMembersCarousel from './TeamMembersCarousel/index.svelte';
import VideoBannerSection from './VideoBannerSection/index.svelte';

export const components = {
	customer_reviews: CustomerReviews,
	hero_with_navigation_overlay: Hero,
	impact_statistics: ImpactNumbers,
	logo_grid: LogoGrid,
	media_grid: MediaGrid,
	multi_block_text_image: MultiBlockTextImage,
	navigational_media_grid: Footer,
	project_showcase: HorizontalShowcase,
	service_highlights: ImageText,
	team_members_carousel: TeamMembersCarousel,
	video_banner_section: VideoBannerSection
};
