// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero/index.svelte';
import ImpactNumbers from './ImpactNumbers/index.svelte';
import HorizontalShowcase from './HorizontalShowcase/index.svelte';
import ImageText from './ImageText/index.svelte';

export const components = {
	hero_with_navigation_overlay: Hero,
	impact_statistics: ImpactNumbers,
	project_showcase: HorizontalShowcase,
	service_highlights: ImageText
};
