// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

type HomepageDocumentDataSlicesSlice = HeroWithNavigationOverlaySlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = HomepageDocument | PageDocument;

/**
 * Item in *Hero → Parallax → Primary → Column 1*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item {}

/**
 * Item in *Hero → Parallax → Primary → Column 2*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item {}

/**
 * Item in *Hero → Parallax → Primary → Column 3*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item {}

/**
 * Primary content in *Hero → Fullscreen → Primary*
 */
export interface HeroWithNavigationOverlaySliceImageLeftHeadlineBottomCtaRightPrimary {
	/**
	 * Headline field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.image_left_headline_bottom_cta_right.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;

	/**
	 * Subheadline field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.image_left_headline_bottom_cta_right.primary.subheadline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheadline: prismic.RichTextField;

	/**
	 * Call to Action Link field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.image_left_headline_bottom_cta_right.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video URL field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.image_left_headline_bottom_cta_right.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Fullscreen variation for Hero Slice
 *
 * - **API ID**: `image_left_headline_bottom_cta_right`
 * - **Description**: This variation features the logo top left, navigation top right, headline and description bottom left, and a right-aligned call-to-action link overlayed on an image background.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySliceImageLeftHeadlineBottomCtaRight =
	prismic.SharedSliceVariation<
		'image_left_headline_bottom_cta_right',
		Simplify<HeroWithNavigationOverlaySliceImageLeftHeadlineBottomCtaRightPrimary>,
		never
	>;

/**
 * Primary content in *Hero → Parallax → Primary*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimary {
	/**
	 * Headline field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;

	/**
	 * Subheadline field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.subheadline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheadline: prismic.RichTextField;

	/**
	 * Call to Action Link field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video URL field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * Column 1 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_1[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_1: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item>>;

	/**
	 * Column 2 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_2[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_2: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item>>;

	/**
	 * Column 3 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_3[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_3: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item>>;
}

/**
 * Parallax variation for Hero Slice
 *
 * - **API ID**: `parallax`
 * - **Description**: This variation features the logo top left, navigation top right, headline and description bottom left, and a right-aligned call-to-action link overlayed on an image background.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySliceParallax = prismic.SharedSliceVariation<
	'parallax',
	Simplify<HeroWithNavigationOverlaySliceParallaxPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroWithNavigationOverlaySliceVariation =
	| HeroWithNavigationOverlaySliceImageLeftHeadlineBottomCtaRight
	| HeroWithNavigationOverlaySliceParallax;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_with_navigation_overlay`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySlice = prismic.SharedSlice<
	'hero_with_navigation_overlay',
	HeroWithNavigationOverlaySliceVariation
>;

/**
 * Item in *ImpactNumbers → Default → Primary → Statistics*
 */
export interface ImpactStatisticsSliceDefaultPrimaryStatsItem {
	/**
	 * Image field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Value field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	value: prismic.KeyTextField;

	/**
	 * Label field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Description field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Primary content in *ImpactNumbers → Default → Primary*
 */
export interface ImpactStatisticsSliceDefaultPrimary {
	/**
	 * Section eyebrow field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: impact_statistics.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Section title field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title
	 * - **API ID Path**: impact_statistics.default.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Section description field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Statistics field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	stats: prismic.GroupField<Simplify<ImpactStatisticsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for ImpactNumbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading, introduction text, and a group of statistical blocks, each featuring an image, numeric value, label, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatisticsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImpactStatisticsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ImpactNumbers*
 */
type ImpactStatisticsSliceVariation = ImpactStatisticsSliceDefault;

/**
 * ImpactNumbers Shared Slice
 *
 * - **API ID**: `impact_statistics`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatisticsSlice = prismic.SharedSlice<
	'impact_statistics',
	ImpactStatisticsSliceVariation
>;

/**
 * Item in *HorizontalShowcase → Default → Primary → Featured Projects*
 */
export interface ProjectShowcaseSliceWithFeaturedProjectPrimaryFeaturedProjectsItem {
	/**
	 * Image field in *HorizontalShowcase → Default → Primary → Featured Projects*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.featured_projects[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Project Title field in *HorizontalShowcase → Default → Primary → Featured Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.featured_projects[].title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Project Summary field in *HorizontalShowcase → Default → Primary → Featured Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.featured_projects[].summary
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	summary: prismic.RichTextField;

	/**
	 * Project Link field in *HorizontalShowcase → Default → Primary → Featured Projects*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.featured_projects[].project_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	project_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Category field in *HorizontalShowcase → Default → Primary → Featured Projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.featured_projects[].category
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
}

/**
 * Primary content in *HorizontalShowcase → Default → Primary*
 */
export interface ProjectShowcaseSliceWithFeaturedProjectPrimary {
	/**
	 * Eyebrow field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Section Title field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_title: prismic.RichTextField;

	/**
	 * Section Description field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.section_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_description: prismic.RichTextField;

	/**
	 * CTA Link field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Featured Projects field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.featured_projects[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	featured_projects: prismic.GroupField<
		Simplify<ProjectShowcaseSliceWithFeaturedProjectPrimaryFeaturedProjectsItem>
	>;
}

/**
 * Default variation for HorizontalShowcase Slice
 *
 * - **API ID**: `with_featured_project`
 * - **Description**: Displays section intro and a primary featured project with category tags and project link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceWithFeaturedProject = prismic.SharedSliceVariation<
	'with_featured_project',
	Simplify<ProjectShowcaseSliceWithFeaturedProjectPrimary>,
	never
>;

/**
 * Slice variation for *HorizontalShowcase*
 */
type ProjectShowcaseSliceVariation = ProjectShowcaseSliceWithFeaturedProject;

/**
 * HorizontalShowcase Shared Slice
 *
 * - **API ID**: `project_showcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSlice = prismic.SharedSlice<
	'project_showcase',
	ProjectShowcaseSliceVariation
>;

/**
 * Item in *ImageText → Image & Text Alternating → Primary → Image & text block*
 */
export interface ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem {
	/**
	 * Image right field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].image_right
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	image_right: prismic.BooleanField;

	/**
	 * Image field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Text field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * CTA button field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].cta_button
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ImageText → Image & Text Alternating → Primary*
 */
export interface ServiceHighlightsSliceImageTextAlternatingPrimary {
	/**
	 * Eyebrow field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;

	/**
	 * CTA Link field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Image & text block field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	image_text_block: prismic.GroupField<
		Simplify<ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem>
	>;
}

/**
 * Image & Text Alternating variation for ImageText Slice
 *
 * - **API ID**: `image_text_alternating`
 * - **Description**: Displays each service with image and text side by side, alternating image position per item. Supports headline, link to all services, and a repeatable list of service blocks.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightsSliceImageTextAlternating = prismic.SharedSliceVariation<
	'image_text_alternating',
	Simplify<ServiceHighlightsSliceImageTextAlternatingPrimary>,
	never
>;

/**
 * Slice variation for *ImageText*
 */
type ServiceHighlightsSliceVariation = ServiceHighlightsSliceImageTextAlternating;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `service_highlights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightsSlice = prismic.SharedSlice<
	'service_highlights',
	ServiceHighlightsSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			HeroWithNavigationOverlaySlice,
			HeroWithNavigationOverlaySliceImageLeftHeadlineBottomCtaRightPrimary,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item,
			HeroWithNavigationOverlaySliceParallaxPrimary,
			HeroWithNavigationOverlaySliceVariation,
			HeroWithNavigationOverlaySliceImageLeftHeadlineBottomCtaRight,
			HeroWithNavigationOverlaySliceParallax,
			ImpactStatisticsSlice,
			ImpactStatisticsSliceDefaultPrimaryStatsItem,
			ImpactStatisticsSliceDefaultPrimary,
			ImpactStatisticsSliceVariation,
			ImpactStatisticsSliceDefault,
			ProjectShowcaseSlice,
			ProjectShowcaseSliceWithFeaturedProjectPrimaryFeaturedProjectsItem,
			ProjectShowcaseSliceWithFeaturedProjectPrimary,
			ProjectShowcaseSliceVariation,
			ProjectShowcaseSliceWithFeaturedProject,
			ServiceHighlightsSlice,
			ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem,
			ServiceHighlightsSliceImageTextAlternatingPrimary,
			ServiceHighlightsSliceVariation,
			ServiceHighlightsSliceImageTextAlternating
		};
	}
}
