// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Content for Footer navigation documents
 */
interface FooterNavigationDocumentData {
	/**
	 * Footer navigation item field in *Footer navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.footer_navigation_item
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	footer_navigation_item: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Footer navigation document from Prismic
 *
 * - **API ID**: `footer_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterNavigationDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FooterNavigationDocumentData>,
		'footer_navigation',
		Lang
	>;

/**
 * Content for General settings documents
 */
interface GeneralSettingsDocumentData {
	/**
	 * Site logo field in *General settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general_settings.site_logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	site_logo: prismic.ImageField<never>;

	/**
	 * Site logo dark field in *General settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general_settings.site_logo_dark
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	site_logo_dark: prismic.ImageField<never>;
}

/**
 * General settings document from Prismic
 *
 * - **API ID**: `general_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GeneralSettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<GeneralSettingsDocumentData>,
		'general_settings',
		Lang
	>;

type HomepageDocumentDataSlicesSlice =
	| TextOnlySlice
	| TextWithFeatureGridSlice
	| ProjectsGridWithFiltersSlice
	| MediaGridSlice
	| MultiBlockTextImageSlice
	| CustomerReviewsSlice
	| VideoBannerSectionSlice
	| LogoGridSlice
	| NavigationalMediaGridSlice
	| TeamMembersCarouselSlice
	| ImpactStatisticsSlice
	| ServiceHighlightsSlice
	| ProjectShowcaseSlice
	| HeroWithNavigationOverlaySlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
	 * Page title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.page_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	page_title: prismic.KeyTextField;

	/**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

/**
 * Content for Main navigation documents
 */
interface MainNavigationDocumentData {
	/**
	 * Navigation item field in *Main navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_navigation.navigation_item
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	navigation_item: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Main navigation document from Prismic
 *
 * - **API ID**: `main_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<MainNavigationDocumentData>, 'main_navigation', Lang>;

type PageDocumentDataSlicesSlice =
	| SideBySideMediaSliderSlice
	| ServiceOverviewGridSlice
	| ImageGalleryTwoColumnSlice
	| ContactInfoSidebarSlice
	| ServicesSliderSlice
	| ProjectsGridWithFiltersSlice
	| TextWithFeatureGridSlice
	| TextOnlySlice
	| MediaGridSlice
	| MultiBlockTextImageSlice
	| HeroWithNavigationOverlaySlice
	| ProjectShowcaseSlice
	| ServiceHighlightsSlice
	| TeamMembersCarouselSlice
	| VideoBannerSectionSlice
	| ImpactStatisticsSlice
	| LogoGridSlice
	| CustomerReviewsSlice
	| NavigationalMediaGridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *Project → Tags*
 */
export interface ProjectDocumentDataTagsItem {
	/**
	 * Project tag field in *Project → Tags*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.tags[].project_tag
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project_tag: ContentRelationshipFieldWithData<[{ id: 'project_tag'; fields: ['tag'] }]>;
}

type ProjectDocumentDataSlicesSlice =
	| SideBySideMediaSliderSlice
	| ImageGalleryTwoColumnSlice
	| TextOnlySlice
	| LogoGridSlice
	| NavigationalMediaGridSlice
	| HeroWithNavigationOverlaySlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Tags field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.tags[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<ProjectDocumentDataTagsItem>>;

	/**
	 * Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Project title
	 * - **API ID Path**: project.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Location field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Amsterdam
	 * - **API ID Path**: project.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;

	/**
	 * Project date field in *Project*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.project_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	project_date: prismic.DateField;

	/**
	 * Project type field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: BKT Renovatie
	 * - **API ID Path**: project.project_type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	project_type: prismic.KeyTextField;

	/**
	 * Summary field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Summary in one or two sentences. Make sure this isn't too long!
	 * - **API ID Path**: project.summary
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	summary: prismic.KeyTextField;

	/**
	 * Featured image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	featured_image: prismic.ImageField<never>;

	/**
	 * Slice Zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProjectDocumentData>,
	'project',
	Lang
>;

/**
 * Content for Project tag documents
 */
interface ProjectTagDocumentData {
	/**
	 * Tag field in *Project tag*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_tag.tag
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField;
}

/**
 * Project tag document from Prismic
 *
 * - **API ID**: `project_tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectTagDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProjectTagDocumentData>,
	'project_tag',
	Lang
>;

/**
 * Content for Social media documents
 */
interface SocialMediaDocumentData {
	/**
	 * Social media link field in *Social media*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_media.social_media_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_media_link: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Social media document from Prismic
 *
 * - **API ID**: `social_media`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SocialMediaDocumentData>,
	'social_media',
	Lang
>;

type VacatureDetailDocumentDataSlicesSlice =
	| HeroWithNavigationOverlaySlice
	| SideBySideMediaSliderSlice
	| TextWithFeatureGridSlice
	| ProjectsGridWithFiltersSlice
	| ServiceOverviewGridSlice
	| MediaGridSlice
	| ProjectShowcaseSlice
	| TeamMembersCarouselSlice
	| ImageGalleryTwoColumnSlice
	| VideoBannerSectionSlice
	| ServiceHighlightsSlice
	| ServicesSliderSlice
	| NavigationalMediaGridSlice
	| TextOnlySlice
	| ContactInfoSidebarSlice
	| ImpactStatisticsSlice
	| MultiBlockTextImageSlice
	| CustomerReviewsSlice
	| LogoGridSlice;

/**
 * Content for Vacature detail documents
 */
interface VacatureDetailDocumentData {
	/**
	 * Vacature image field in *Vacature detail*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vacature_detail.vacature_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	vacature_image: prismic.ImageField<never>;

	/**
	 * Vacature Title field in *Vacature detail*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vacature_detail.vacature_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	vacature_title: prismic.KeyTextField;

	/**
	 * Vacature label field in *Vacature detail*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vacature_detail.vacature_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	vacature_label: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Vacature detail*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vacature_detail.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<VacatureDetailDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Vacature detail*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: vacature_detail.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Vacature detail*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: vacature_detail.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Vacature detail*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vacature_detail.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Vacature detail document from Prismic
 *
 * - **API ID**: `vacature_detail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VacatureDetailDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<VacatureDetailDocumentData>,
	'vacature_detail',
	Lang
>;

export type AllDocumentTypes =
	| FooterNavigationDocument
	| GeneralSettingsDocument
	| HomepageDocument
	| MainNavigationDocument
	| PageDocument
	| ProjectDocument
	| ProjectTagDocument
	| SocialMediaDocument
	| VacatureDetailDocument;

/**
 * Item in *ContacSection → Default with Image → Primary → Contact Categories*
 */
export interface ContactInfoSidebarSliceDefaultWithImagePrimaryContactCategoriesItem {
	/**
	 * Category Label field in *ContacSection → Default with Image → Primary → Contact Categories*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info_sidebar.default_with_image.primary.contact_categories[].category_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category_label: prismic.KeyTextField;

	/**
	 * Email Address field in *ContacSection → Default with Image → Primary → Contact Categories*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info_sidebar.default_with_image.primary.contact_categories[].email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;

	/**
	 * Phone Number field in *ContacSection → Default with Image → Primary → Contact Categories*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info_sidebar.default_with_image.primary.contact_categories[].phone_number
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_number: prismic.KeyTextField;
}

/**
 * Primary content in *ContacSection → Default with Image → Primary*
 */
export interface ContactInfoSidebarSliceDefaultWithImagePrimary {
	/**
	 * Contact Categories field in *ContacSection → Default with Image → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info_sidebar.default_with_image.primary.contact_categories[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	contact_categories: prismic.GroupField<
		Simplify<ContactInfoSidebarSliceDefaultWithImagePrimaryContactCategoriesItem>
	>;

	/**
	 * Side Image field in *ContacSection → Default with Image → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info_sidebar.default_with_image.primary.side_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	side_image: prismic.ImageField<never>;
}

/**
 * Default with Image variation for ContacSection Slice
 *
 * - **API ID**: `default_with_image`
 * - **Description**: Contact information sidebar with corresponding image area.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactInfoSidebarSliceDefaultWithImage = prismic.SharedSliceVariation<
	'default_with_image',
	Simplify<ContactInfoSidebarSliceDefaultWithImagePrimary>,
	never
>;

/**
 * Slice variation for *ContacSection*
 */
type ContactInfoSidebarSliceVariation = ContactInfoSidebarSliceDefaultWithImage;

/**
 * ContacSection Shared Slice
 *
 * - **API ID**: `contact_info_sidebar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactInfoSidebarSlice = prismic.SharedSlice<
	'contact_info_sidebar',
	ContactInfoSidebarSliceVariation
>;

/**
 * Item in *CustomerReviews → Default → Primary → Reviews*
 */
export interface CustomerReviewsSliceDefaultPrimaryReviewsItem {
	/**
	 * avatar field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].avatar
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	avatar: prismic.ImageField<never>;

	/**
	 * name field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;

	/**
	 * date field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;

	/**
	 * rating field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].rating
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	rating: prismic.SelectField<'1' | '2' | '3' | '4' | '5'>;

	/**
	 * content field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Primary content in *CustomerReviews → Default → Primary*
 */
export interface CustomerReviewsSliceDefaultPrimary {
	/**
	 * Eyebrow field in *CustomerReviews → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *CustomerReviews → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Reviews field in *CustomerReviews → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	reviews: prismic.GroupField<Simplify<CustomerReviewsSliceDefaultPrimaryReviewsItem>>;
}

/**
 * Default variation for CustomerReviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CustomerReviewsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CustomerReviewsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CustomerReviews*
 */
type CustomerReviewsSliceVariation = CustomerReviewsSliceDefault;

/**
 * CustomerReviews Shared Slice
 *
 * - **API ID**: `customer_reviews`
 * - **Description**: CustomerReviews
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CustomerReviewsSlice = prismic.SharedSlice<
	'customer_reviews',
	CustomerReviewsSliceVariation
>;

/**
 * Item in *Hero → Parallax → Primary → Column 1*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item {
	/**
	 * Item field in *Hero → Parallax → Primary → Column 1*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_1[].item
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	item: prismic.RichTextField;
}

/**
 * Item in *Hero → Parallax → Primary → Column 2*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item {
	/**
	 * Item field in *Hero → Parallax → Primary → Column 2*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_2[].item
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	item: prismic.RichTextField;
}

/**
 * Item in *Hero → Parallax → Primary → Column 3*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item {
	/**
	 * Item field in *Hero → Parallax → Primary → Column 3*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_3[].item
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	item: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Parallax → Primary*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimary {
	/**
	 * Eyebrow field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Video URL field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * Poster image field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.poster_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	poster_image: prismic.ImageField<never>;

	/**
	 * Column 1 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_1[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_1: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item>>;

	/**
	 * Column 2 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_2[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_2: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item>>;

	/**
	 * Column 3 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_3[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_3: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item>>;
}

/**
 * Parallax variation for Hero Slice
 *
 * - **API ID**: `parallax`
 * - **Description**: This variation features the logo top left, navigation top right, headline and description bottom left, and a right-aligned call-to-action link overlayed on an image background.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySliceParallax = prismic.SharedSliceVariation<
	'parallax',
	Simplify<HeroWithNavigationOverlaySliceParallaxPrimary>,
	never
>;

/**
 * Primary content in *Hero → Fullscreen → Primary*
 */
export interface HeroWithNavigationOverlaySliceFullscreenPrimary {
	/**
	 * Headline field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;

	/**
	 * Subheadline field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.subheadline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheadline: prismic.RichTextField;

	/**
	 * eyebrow field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	eyebrow: prismic.RichTextField;

	/**
	 * Call to Action Link field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video URL field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * Image field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Add overlay field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.add_overlay
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	add_overlay: prismic.BooleanField;
}

/**
 * Fullscreen variation for Hero Slice
 *
 * - **API ID**: `fullscreen`
 * - **Description**: This variation features the logo top left, navigation top right, headline and description bottom left, and a right-aligned call-to-action link overlayed on an image background.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySliceFullscreen = prismic.SharedSliceVariation<
	'fullscreen',
	Simplify<HeroWithNavigationOverlaySliceFullscreenPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroWithNavigationOverlaySliceVariation =
	| HeroWithNavigationOverlaySliceParallax
	| HeroWithNavigationOverlaySliceFullscreen;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_with_navigation_overlay`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySlice = prismic.SharedSlice<
	'hero_with_navigation_overlay',
	HeroWithNavigationOverlaySliceVariation
>;

/**
 * Item in *SimpleMediaGallery → Default → Primary → Media*
 */
export interface ImageGalleryTwoColumnSliceDefaultPrimaryMediaItem {
	/**
	 * Image (used as poster if video) field in *SimpleMediaGallery → Default → Primary → Media*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery_two_column.default.primary.media[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *SimpleMediaGallery → Default → Primary → Media*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery_two_column.default.primary.media[].video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *SimpleMediaGallery → Default → Primary*
 */
export interface ImageGalleryTwoColumnSliceDefaultPrimary {
	/**
	 * Media field in *SimpleMediaGallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery_two_column.default.primary.media[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	media: prismic.GroupField<Simplify<ImageGalleryTwoColumnSliceDefaultPrimaryMediaItem>>;
}

/**
 * Default variation for SimpleMediaGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays two images in a two-column gallery layout.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGalleryTwoColumnSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageGalleryTwoColumnSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SimpleMediaGallery*
 */
type ImageGalleryTwoColumnSliceVariation = ImageGalleryTwoColumnSliceDefault;

/**
 * SimpleMediaGallery Shared Slice
 *
 * - **API ID**: `image_gallery_two_column`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGalleryTwoColumnSlice = prismic.SharedSlice<
	'image_gallery_two_column',
	ImageGalleryTwoColumnSliceVariation
>;

/**
 * Item in *ImpactNumbers → Default → Primary → Statistics*
 */
export interface ImpactStatisticsSliceDefaultPrimaryStatsItem {
	/**
	 * Image field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Value field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	value: prismic.KeyTextField;

	/**
	 * Label field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Description field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;

	/**
	 * Number symbol field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: %
	 * - **API ID Path**: impact_statistics.default.primary.stats[].number_symbol
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	number_symbol: prismic.KeyTextField;
}

/**
 * Primary content in *ImpactNumbers → Default → Primary*
 */
export interface ImpactStatisticsSliceDefaultPrimary {
	/**
	 * Light or dark? field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: impact_statistics.default.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: impact_statistics.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * CTA Link field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Statistics field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	stats: prismic.GroupField<Simplify<ImpactStatisticsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for ImpactNumbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading, introduction text, and a group of statistical blocks, each featuring an image, numeric value, label, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatisticsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImpactStatisticsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ImpactNumbers*
 */
type ImpactStatisticsSliceVariation = ImpactStatisticsSliceDefault;

/**
 * ImpactNumbers Shared Slice
 *
 * - **API ID**: `impact_statistics`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatisticsSlice = prismic.SharedSlice<
	'impact_statistics',
	ImpactStatisticsSliceVariation
>;

/**
 * Item in *LogoGrid → Default Grid → Primary → Logos*
 */
export interface LogoGridSliceDefaultGridPrimaryLogosItem {
	/**
	 * Logo Image field in *LogoGrid → Default Grid → Primary → Logos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_grid.default_grid.primary.logos[].logo_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoGrid → Default Grid → Primary*
 */
export interface LogoGridSliceDefaultGridPrimary {
	/**
	 * Section eyebrow field in *LogoGrid → Default Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Section eyebrow
	 * - **API ID Path**: logo_grid.default_grid.primary.section_eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_eyebrow: prismic.KeyTextField;

	/**
	 * Section title field in *LogoGrid → Default Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Section title
	 * - **API ID Path**: logo_grid.default_grid.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Logos field in *LogoGrid → Default Grid → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_grid.default_grid.primary.logos[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	logos: prismic.GroupField<Simplify<LogoGridSliceDefaultGridPrimaryLogosItem>>;
}

/**
 * Default Grid variation for LogoGrid Slice
 *
 * - **API ID**: `default_grid`
 * - **Description**: A standard grid of logos with support for image- or text-based logos and optional link on each logo.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoGridSliceDefaultGrid = prismic.SharedSliceVariation<
	'default_grid',
	Simplify<LogoGridSliceDefaultGridPrimary>,
	never
>;

/**
 * Slice variation for *LogoGrid*
 */
type LogoGridSliceVariation = LogoGridSliceDefaultGrid;

/**
 * LogoGrid Shared Slice
 *
 * - **API ID**: `logo_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoGridSlice = prismic.SharedSlice<'logo_grid', LogoGridSliceVariation>;

/**
 * Item in *MediaGrid → Heading, Description & Image Grid → Primary → Items*
 */
export interface MediaGridSliceHeadingDescriptionImageGridPrimaryItemsItem {
	/**
	 * Image field in *MediaGrid → Heading, Description & Image Grid → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video URL field in *MediaGrid → Heading, Description & Image Grid → Primary → Items*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.items[].video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *MediaGrid → Heading, Description & Image Grid → Primary*
 */
export interface MediaGridSliceHeadingDescriptionImageGridPrimary {
	/**
	 * Light or dark field in *MediaGrid → Heading, Description & Image Grid → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.light_or_dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	light_or_dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *MediaGrid → Heading, Description & Image Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Heading field in *MediaGrid → Heading, Description & Image Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Description field in *MediaGrid → Heading, Description & Image Grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * CTA Link field in *MediaGrid → Heading, Description & Image Grid → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Items field in *MediaGrid → Heading, Description & Image Grid → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_grid.heading_description_image_grid.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<MediaGridSliceHeadingDescriptionImageGridPrimaryItemsItem>>;
}

/**
 * Heading, Description & Image Grid variation for MediaGrid Slice
 *
 * - **API ID**: `heading_description_image_grid`
 * - **Description**: Displays a grid of images with a main heading and short description above.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGridSliceHeadingDescriptionImageGrid = prismic.SharedSliceVariation<
	'heading_description_image_grid',
	Simplify<MediaGridSliceHeadingDescriptionImageGridPrimary>,
	never
>;

/**
 * Slice variation for *MediaGrid*
 */
type MediaGridSliceVariation = MediaGridSliceHeadingDescriptionImageGrid;

/**
 * MediaGrid Shared Slice
 *
 * - **API ID**: `media_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGridSlice = prismic.SharedSlice<'media_grid', MediaGridSliceVariation>;

/**
 * Item in *MultiBlockTextImage → Multiple Text Blocks with Side Image → Primary → Blocks*
 */
export interface MultiBlockTextImageSliceMultipleBlocksWithSideImagePrimaryBlocksItem {
	/**
	 * Title field in *MultiBlockTextImage → Multiple Text Blocks with Side Image → Primary → Blocks*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: multi_block_text_image.multiple_blocks_with_side_image.primary.blocks[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *MultiBlockTextImage → Multiple Text Blocks with Side Image → Primary → Blocks*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: multi_block_text_image.multiple_blocks_with_side_image.primary.blocks[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *MultiBlockTextImage → Multiple Text Blocks with Side Image → Primary*
 */
export interface MultiBlockTextImageSliceMultipleBlocksWithSideImagePrimary {
	/**
	 * Blocks field in *MultiBlockTextImage → Multiple Text Blocks with Side Image → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: multi_block_text_image.multiple_blocks_with_side_image.primary.blocks[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	blocks: prismic.GroupField<
		Simplify<MultiBlockTextImageSliceMultipleBlocksWithSideImagePrimaryBlocksItem>
	>;

	/**
	 * Side image field in *MultiBlockTextImage → Multiple Text Blocks with Side Image → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: multi_block_text_image.multiple_blocks_with_side_image.primary.side_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	side_image: prismic.ImageField<never>;
}

/**
 * Multiple Text Blocks with Side Image variation for MultiBlockTextImage Slice
 *
 * - **API ID**: `multiple_blocks_with_side_image`
 * - **Description**: Displays multiple content blocks (each with a title and description) aligned left, paired with an image on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MultiBlockTextImageSliceMultipleBlocksWithSideImage = prismic.SharedSliceVariation<
	'multiple_blocks_with_side_image',
	Simplify<MultiBlockTextImageSliceMultipleBlocksWithSideImagePrimary>,
	never
>;

/**
 * Slice variation for *MultiBlockTextImage*
 */
type MultiBlockTextImageSliceVariation = MultiBlockTextImageSliceMultipleBlocksWithSideImage;

/**
 * MultiBlockTextImage Shared Slice
 *
 * - **API ID**: `multi_block_text_image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MultiBlockTextImageSlice = prismic.SharedSlice<
	'multi_block_text_image',
	MultiBlockTextImageSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Navigation items*
 */
export interface NavigationalMediaGridSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Footer → Default → Primary → Navigation items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[].media
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	media: prismic.ImageField<never>;

	/**
	 * Label field in *Footer → Default → Primary → Navigation items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Destination link field in *Footer → Default → Primary → Navigation items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[].destination
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	destination: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface NavigationalMediaGridSliceDefaultPrimary {
	/**
	 * Navigation items field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<NavigationalMediaGridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard grid navigation with image backgrounds and labels.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationalMediaGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationalMediaGridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Footer*
 */
type NavigationalMediaGridSliceVariation = NavigationalMediaGridSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `navigational_media_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationalMediaGridSlice = prismic.SharedSlice<
	'navigational_media_grid',
	NavigationalMediaGridSliceVariation
>;

/**
 * Item in *HorizontalShowcase → Default → Primary → Projects*
 */
export interface ProjectShowcaseSliceWithFeaturedProjectPrimaryProjectsItem {
	/**
	 * Project field in *HorizontalShowcase → Default → Primary → Projects*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.projects[].project
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project: ContentRelationshipFieldWithData<
		[
			{
				id: 'project';
				fields: ['title', 'location', 'featured_image', { id: 'tags'; fields: ['tag'] }, 'summary'];
			}
		]
	>;
}

/**
 * Primary content in *HorizontalShowcase → Default → Primary*
 */
export interface ProjectShowcaseSliceWithFeaturedProjectPrimary {
	/**
	 * Light or dark? field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: project_showcase.with_featured_project.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * CTA Link field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Projects field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.projects[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	projects: prismic.GroupField<
		Simplify<ProjectShowcaseSliceWithFeaturedProjectPrimaryProjectsItem>
	>;
}

/**
 * Default variation for HorizontalShowcase Slice
 *
 * - **API ID**: `with_featured_project`
 * - **Description**: Displays section intro and a primary featured project with category tags and project link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceWithFeaturedProject = prismic.SharedSliceVariation<
	'with_featured_project',
	Simplify<ProjectShowcaseSliceWithFeaturedProjectPrimary>,
	never
>;

/**
 * Slice variation for *HorizontalShowcase*
 */
type ProjectShowcaseSliceVariation = ProjectShowcaseSliceWithFeaturedProject;

/**
 * HorizontalShowcase Shared Slice
 *
 * - **API ID**: `project_showcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSlice = prismic.SharedSlice<
	'project_showcase',
	ProjectShowcaseSliceVariation
>;

/**
 * Item in *ProjectsGridWithFilters → Default → Primary → Projects*
 */
export interface ProjectsGridWithFiltersSliceDefaultPrimaryProjectsItem {
	/**
	 * Project field in *ProjectsGridWithFilters → Default → Primary → Projects*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_grid_with_filters.default.primary.projects[].project
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project: ContentRelationshipFieldWithData<
		[
			{
				id: 'project';
				fields: [
					'title',
					'project_date',
					'project_type',
					'summary',
					'featured_image',
					{
						id: 'tags';
						fields: [{ id: 'project_tag'; customtypes: [{ id: 'project_tag'; fields: ['tag'] }] }];
					}
				];
			}
		]
	>;
}

/**
 * Primary content in *ProjectsGridWithFilters → Default → Primary*
 */
export interface ProjectsGridWithFiltersSliceDefaultPrimary {
	/**
	 * Projects field in *ProjectsGridWithFilters → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_grid_with_filters.default.primary.projects[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	projects: prismic.GroupField<Simplify<ProjectsGridWithFiltersSliceDefaultPrimaryProjectsItem>>;
}

/**
 * Default variation for ProjectsGridWithFilters Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsGridWithFiltersSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProjectsGridWithFiltersSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ProjectsGridWithFilters*
 */
type ProjectsGridWithFiltersSliceVariation = ProjectsGridWithFiltersSliceDefault;

/**
 * ProjectsGridWithFilters Shared Slice
 *
 * - **API ID**: `projects_grid_with_filters`
 * - **Description**: ProjectsGridWithFilters
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsGridWithFiltersSlice = prismic.SharedSlice<
	'projects_grid_with_filters',
	ProjectsGridWithFiltersSliceVariation
>;

/**
 * Item in *ImageText → Image & Text Alternating → Primary → Image & text block*
 */
export interface ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem {
	/**
	 * Image right field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].image_right
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	image_right: prismic.BooleanField;

	/**
	 * Image field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Text field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * CTA button field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].cta_button
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ImageText → Image & Text Alternating → Primary*
 */
export interface ServiceHighlightsSliceImageTextAlternatingPrimary {
	/**
	 * Light or dark? field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * CTA Link field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Image & text block field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	image_text_block: prismic.GroupField<
		Simplify<ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem>
	>;
}

/**
 * Image & Text Alternating variation for ImageText Slice
 *
 * - **API ID**: `image_text_alternating`
 * - **Description**: Displays each service with image and text side by side, alternating image position per item. Supports headline, link to all services, and a repeatable list of service blocks.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightsSliceImageTextAlternating = prismic.SharedSliceVariation<
	'image_text_alternating',
	Simplify<ServiceHighlightsSliceImageTextAlternatingPrimary>,
	never
>;

/**
 * Slice variation for *ImageText*
 */
type ServiceHighlightsSliceVariation = ServiceHighlightsSliceImageTextAlternating;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `service_highlights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightsSlice = prismic.SharedSlice<
	'service_highlights',
	ServiceHighlightsSliceVariation
>;

/**
 * Item in *VacaturesGrid → Default → Primary → Vacatures*
 */
export interface ServiceOverviewGridSliceDefaultPrimaryVacaturesItem {
	/**
	 * Vacature field in *VacaturesGrid → Default → Primary → Vacatures*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview_grid.default.primary.vacatures[].vacature
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	vacature: ContentRelationshipFieldWithData<
		[{ id: 'vacature_detail'; fields: ['vacature_image', 'vacature_title', 'vacature_label'] }]
	>;
}

/**
 * Primary content in *VacaturesGrid → Default → Primary*
 */
export interface ServiceOverviewGridSliceDefaultPrimary {
	/**
	 * Vacatures field in *VacaturesGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview_grid.default.primary.vacatures[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	vacatures: prismic.GroupField<Simplify<ServiceOverviewGridSliceDefaultPrimaryVacaturesItem>>;
}

/**
 * Default variation for VacaturesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard 2x2 or responsive grid of service/feature cards with image, label, title, and link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceOverviewGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ServiceOverviewGridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VacaturesGrid*
 */
type ServiceOverviewGridSliceVariation = ServiceOverviewGridSliceDefault;

/**
 * VacaturesGrid Shared Slice
 *
 * - **API ID**: `service_overview_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceOverviewGridSlice = prismic.SharedSlice<
	'service_overview_grid',
	ServiceOverviewGridSliceVariation
>;

/**
 * Item in *ServicesSlider → Default → Primary → Projects*
 */
export interface ServicesSliderSliceDefaultPrimaryProjectsItem {
	/**
	 * Service title field in *ServicesSlider → Default → Primary → Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Service title
	 * - **API ID Path**: services_slider.default.primary.projects[].service_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	service_title: prismic.RichTextField;

	/**
	 * Project field in *ServicesSlider → Default → Primary → Projects*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_slider.default.primary.projects[].project
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project: ContentRelationshipFieldWithData<
		[
			{
				id: 'project';
				fields: ['title', 'location', 'summary', 'featured_image', { id: 'tags'; fields: ['tag'] }];
			}
		]
	>;

	/**
	 * Service text field in *ServicesSlider → Default → Primary → Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Service text
	 * - **API ID Path**: services_slider.default.primary.projects[].service_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	service_text: prismic.RichTextField;
}

/**
 * Primary content in *ServicesSlider → Default → Primary*
 */
export interface ServicesSliderSliceDefaultPrimary {
	/**
	 * Section title field in *ServicesSlider → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Dagelijks onderhoud
	 * - **API ID Path**: services_slider.default.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_title: prismic.RichTextField;

	/**
	 * Projects field in *ServicesSlider → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_slider.default.primary.projects[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	projects: prismic.GroupField<Simplify<ServicesSliderSliceDefaultPrimaryProjectsItem>>;
}

/**
 * Default variation for ServicesSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliderSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ServicesSliderSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ServicesSlider*
 */
type ServicesSliderSliceVariation = ServicesSliderSliceDefault;

/**
 * ServicesSlider Shared Slice
 *
 * - **API ID**: `services_slider`
 * - **Description**: ServicesSlider
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliderSlice = prismic.SharedSlice<
	'services_slider',
	ServicesSliderSliceVariation
>;

/**
 * Primary content in *BeforeAndAfterSlider → Default → Primary*
 */
export interface SideBySideMediaSliderSliceDefaultPrimary {
	/**
	 * Before field in *BeforeAndAfterSlider → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: side_by_side_media_slider.default.primary.before
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	before: prismic.ImageField<never>;

	/**
	 * After field in *BeforeAndAfterSlider → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: side_by_side_media_slider.default.primary.after
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	after: prismic.ImageField<never>;
}

/**
 * Default variation for BeforeAndAfterSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays two images side by side with navigation or reveal slider.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideBySideMediaSliderSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SideBySideMediaSliderSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BeforeAndAfterSlider*
 */
type SideBySideMediaSliderSliceVariation = SideBySideMediaSliderSliceDefault;

/**
 * BeforeAndAfterSlider Shared Slice
 *
 * - **API ID**: `side_by_side_media_slider`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideBySideMediaSliderSlice = prismic.SharedSlice<
	'side_by_side_media_slider',
	SideBySideMediaSliderSliceVariation
>;

/**
 * Item in *TeamMembersCarousel → Default → Primary → Team Members*
 */
export interface TeamMembersCarouselSliceDefaultPrimaryTeamMembersItem {
	/**
	 * Photo field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].photo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	photo: prismic.ImageField<never>;

	/**
	 * Name field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;

	/**
	 * Role field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].role
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;

	/**
	 * LinkedIn Link field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].social_linkedin
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_linkedin: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *TeamMembersCarousel → Default → Primary*
 */
export interface TeamMembersCarouselSliceDefaultPrimary {
	/**
	 * Light or dark? field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: team_members_carousel.default.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Section Eyebrow field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: team_members_carousel.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Section Title field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title
	 * - **API ID Path**: team_members_carousel.default.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Section Description field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Description
	 * - **API ID Path**: team_members_carousel.default.primary.section_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_description: prismic.RichTextField;

	/**
	 * CTA Link field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Team Members field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	team_members: prismic.GroupField<Simplify<TeamMembersCarouselSliceDefaultPrimaryTeamMembersItem>>;
}

/**
 * Default variation for TeamMembersCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Carousel layout for showcasing multiple team members, including contact call-to-action and intro heading/description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMembersCarouselSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TeamMembersCarouselSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TeamMembersCarousel*
 */
type TeamMembersCarouselSliceVariation = TeamMembersCarouselSliceDefault;

/**
 * TeamMembersCarousel Shared Slice
 *
 * - **API ID**: `team_members_carousel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMembersCarouselSlice = prismic.SharedSlice<
	'team_members_carousel',
	TeamMembersCarouselSliceVariation
>;

/**
 * Primary content in *TextOnly → Default → Primary*
 */
export interface TextOnlySliceDefaultPrimary {
	/**
	 * Title field in *TextOnly → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Title
	 * - **API ID Path**: text_only.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Text field in *TextOnly → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Text
	 * - **API ID Path**: text_only.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for TextOnly Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextOnlySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextOnlySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextOnly*
 */
type TextOnlySliceVariation = TextOnlySliceDefault;

/**
 * TextOnly Shared Slice
 *
 * - **API ID**: `text_only`
 * - **Description**: TextOnly
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextOnlySlice = prismic.SharedSlice<'text_only', TextOnlySliceVariation>;

/**
 * Item in *TextWithFeatureGrid → Default → Primary → Features*
 */
export interface TextWithFeatureGridSliceDefaultPrimaryFeaturesItem {
	/**
	 * Feature Title field in *TextWithFeatureGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.features[].feature_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_title: prismic.KeyTextField;

	/**
	 * Feature Bullets field in *TextWithFeatureGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.features[].feature_bullets
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	feature_bullets: prismic.RichTextField;
}

/**
 * Primary content in *TextWithFeatureGrid → Default → Primary*
 */
export interface TextWithFeatureGridSliceDefaultPrimary {
	/**
	 * Eyebrow field in *TextWithFeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *TextWithFeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Description field in *TextWithFeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Background image field in *TextWithFeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * Features field in *TextWithFeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_feature_grid.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<TextWithFeatureGridSliceDefaultPrimaryFeaturesItem>>;

	/**
	 * Should the text be light or dark? field in *TextWithFeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: text_with_feature_grid.default.primary.text_is_dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	text_is_dark: prismic.BooleanField;
}

/**
 * Default variation for TextWithFeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: A main headline, intro text, and a flexible grid of multiple feature boxes with titles and bullet points.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithFeatureGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextWithFeatureGridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextWithFeatureGrid*
 */
type TextWithFeatureGridSliceVariation = TextWithFeatureGridSliceDefault;

/**
 * TextWithFeatureGrid Shared Slice
 *
 * - **API ID**: `text_with_feature_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithFeatureGridSlice = prismic.SharedSlice<
	'text_with_feature_grid',
	TextWithFeatureGridSliceVariation
>;

/**
 * Primary content in *VideoBannerSection → Default → Primary*
 */
export interface VideoBannerSectionSliceDefaultPrimary {
	/**
	 * Headline field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Content field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * CTA link field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * Poster image field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.poster_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	poster_image: prismic.ImageField<never>;
}

/**
 * Default variation for VideoBannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoBannerSectionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoBannerSectionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VideoBannerSection*
 */
type VideoBannerSectionSliceVariation = VideoBannerSectionSliceDefault;

/**
 * VideoBannerSection Shared Slice
 *
 * - **API ID**: `video_banner_section`
 * - **Description**: VideoBannerSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoBannerSectionSlice = prismic.SharedSlice<
	'video_banner_section',
	VideoBannerSectionSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterNavigationDocument,
			FooterNavigationDocumentData,
			GeneralSettingsDocument,
			GeneralSettingsDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			MainNavigationDocument,
			MainNavigationDocumentData,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataTagsItem,
			ProjectDocumentDataSlicesSlice,
			ProjectTagDocument,
			ProjectTagDocumentData,
			SocialMediaDocument,
			SocialMediaDocumentData,
			VacatureDetailDocument,
			VacatureDetailDocumentData,
			VacatureDetailDocumentDataSlicesSlice,
			AllDocumentTypes,
			ContactInfoSidebarSlice,
			ContactInfoSidebarSliceDefaultWithImagePrimaryContactCategoriesItem,
			ContactInfoSidebarSliceDefaultWithImagePrimary,
			ContactInfoSidebarSliceVariation,
			ContactInfoSidebarSliceDefaultWithImage,
			CustomerReviewsSlice,
			CustomerReviewsSliceDefaultPrimaryReviewsItem,
			CustomerReviewsSliceDefaultPrimary,
			CustomerReviewsSliceVariation,
			CustomerReviewsSliceDefault,
			HeroWithNavigationOverlaySlice,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item,
			HeroWithNavigationOverlaySliceParallaxPrimary,
			HeroWithNavigationOverlaySliceFullscreenPrimary,
			HeroWithNavigationOverlaySliceVariation,
			HeroWithNavigationOverlaySliceParallax,
			HeroWithNavigationOverlaySliceFullscreen,
			ImageGalleryTwoColumnSlice,
			ImageGalleryTwoColumnSliceDefaultPrimaryMediaItem,
			ImageGalleryTwoColumnSliceDefaultPrimary,
			ImageGalleryTwoColumnSliceVariation,
			ImageGalleryTwoColumnSliceDefault,
			ImpactStatisticsSlice,
			ImpactStatisticsSliceDefaultPrimaryStatsItem,
			ImpactStatisticsSliceDefaultPrimary,
			ImpactStatisticsSliceVariation,
			ImpactStatisticsSliceDefault,
			LogoGridSlice,
			LogoGridSliceDefaultGridPrimaryLogosItem,
			LogoGridSliceDefaultGridPrimary,
			LogoGridSliceVariation,
			LogoGridSliceDefaultGrid,
			MediaGridSlice,
			MediaGridSliceHeadingDescriptionImageGridPrimaryItemsItem,
			MediaGridSliceHeadingDescriptionImageGridPrimary,
			MediaGridSliceVariation,
			MediaGridSliceHeadingDescriptionImageGrid,
			MultiBlockTextImageSlice,
			MultiBlockTextImageSliceMultipleBlocksWithSideImagePrimaryBlocksItem,
			MultiBlockTextImageSliceMultipleBlocksWithSideImagePrimary,
			MultiBlockTextImageSliceVariation,
			MultiBlockTextImageSliceMultipleBlocksWithSideImage,
			NavigationalMediaGridSlice,
			NavigationalMediaGridSliceDefaultPrimaryItemsItem,
			NavigationalMediaGridSliceDefaultPrimary,
			NavigationalMediaGridSliceVariation,
			NavigationalMediaGridSliceDefault,
			ProjectShowcaseSlice,
			ProjectShowcaseSliceWithFeaturedProjectPrimaryProjectsItem,
			ProjectShowcaseSliceWithFeaturedProjectPrimary,
			ProjectShowcaseSliceVariation,
			ProjectShowcaseSliceWithFeaturedProject,
			ProjectsGridWithFiltersSlice,
			ProjectsGridWithFiltersSliceDefaultPrimaryProjectsItem,
			ProjectsGridWithFiltersSliceDefaultPrimary,
			ProjectsGridWithFiltersSliceVariation,
			ProjectsGridWithFiltersSliceDefault,
			ServiceHighlightsSlice,
			ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem,
			ServiceHighlightsSliceImageTextAlternatingPrimary,
			ServiceHighlightsSliceVariation,
			ServiceHighlightsSliceImageTextAlternating,
			ServiceOverviewGridSlice,
			ServiceOverviewGridSliceDefaultPrimaryVacaturesItem,
			ServiceOverviewGridSliceDefaultPrimary,
			ServiceOverviewGridSliceVariation,
			ServiceOverviewGridSliceDefault,
			ServicesSliderSlice,
			ServicesSliderSliceDefaultPrimaryProjectsItem,
			ServicesSliderSliceDefaultPrimary,
			ServicesSliderSliceVariation,
			ServicesSliderSliceDefault,
			SideBySideMediaSliderSlice,
			SideBySideMediaSliderSliceDefaultPrimary,
			SideBySideMediaSliderSliceVariation,
			SideBySideMediaSliderSliceDefault,
			TeamMembersCarouselSlice,
			TeamMembersCarouselSliceDefaultPrimaryTeamMembersItem,
			TeamMembersCarouselSliceDefaultPrimary,
			TeamMembersCarouselSliceVariation,
			TeamMembersCarouselSliceDefault,
			TextOnlySlice,
			TextOnlySliceDefaultPrimary,
			TextOnlySliceVariation,
			TextOnlySliceDefault,
			TextWithFeatureGridSlice,
			TextWithFeatureGridSliceDefaultPrimaryFeaturesItem,
			TextWithFeatureGridSliceDefaultPrimary,
			TextWithFeatureGridSliceVariation,
			TextWithFeatureGridSliceDefault,
			VideoBannerSectionSlice,
			VideoBannerSectionSliceDefaultPrimary,
			VideoBannerSectionSliceVariation,
			VideoBannerSectionSliceDefault
		};
	}
}
