// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Content for Footer navigation documents
 */
interface FooterNavigationDocumentData {
	/**
	 * Footer navigation item field in *Footer navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.footer_navigation_item
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	footer_navigation_item: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Footer navigation document from Prismic
 *
 * - **API ID**: `footer_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterNavigationDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FooterNavigationDocumentData>,
		'footer_navigation',
		Lang
	>;

/**
 * Content for General settings documents
 */
interface GeneralSettingsDocumentData {
	/**
	 * Site logo field in *General settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general_settings.site_logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	site_logo: prismic.ImageField<never>;

	/**
	 * Site logo dark field in *General settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general_settings.site_logo_dark
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	site_logo_dark: prismic.ImageField<never>;
}

/**
 * General settings document from Prismic
 *
 * - **API ID**: `general_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GeneralSettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<GeneralSettingsDocumentData>,
		'general_settings',
		Lang
	>;

type HomepageDocumentDataSlicesSlice =
	| CustomerReviewsSlice
	| VideoBannerSectionSlice
	| LogoGridSlice
	| NavigationalMediaGridSlice
	| TeamMembersCarouselSlice
	| ImpactStatisticsSlice
	| ServiceHighlightsSlice
	| ProjectShowcaseSlice
	| HeroWithNavigationOverlaySlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
	 * Page title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.page_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	page_title: prismic.KeyTextField;

	/**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

/**
 * Content for Main navigation documents
 */
interface MainNavigationDocumentData {
	/**
	 * Navigation item field in *Main navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_navigation.navigation_item
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	navigation_item: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Main navigation document from Prismic
 *
 * - **API ID**: `main_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<MainNavigationDocumentData>, 'main_navigation', Lang>;

type PageDocumentDataSlicesSlice = NavigationalMediaGridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *Project → Gallery*
 */
export interface ProjectDocumentDataGalleryItem {
	/**
	 * Item content field in *Project → Gallery*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.gallery[].item_content
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	item_content: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Item in *Project → Tags*
 */
export interface ProjectDocumentDataTagsItem {
	/**
	 * Tag field in *Project → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Project title
	 * - **API ID Path**: project.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Location field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Amsterdam
	 * - **API ID Path**: project.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;

	/**
	 * Project date field in *Project*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.project_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	project_date: prismic.DateField;

	/**
	 * Project type field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: BKT Renovatie
	 * - **API ID Path**: project.project_type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	project_type: prismic.KeyTextField;

	/**
	 * Summary field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Summary in one or two sentences. Make sure this isn't too long!
	 * - **API ID Path**: project.summary
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	summary: prismic.KeyTextField;

	/**
	 * content_1 field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: First content section goes here
	 * - **API ID Path**: project.content_1
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content_1: prismic.RichTextField;

	/**
	 * content_2 field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Second content section goes here
	 * - **API ID Path**: project.content_2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content_2: prismic.RichTextField;

	/**
	 * featured_image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	featured_image: prismic.ImageField<never>;

	/**
	 * Gallery field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.gallery[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	gallery: prismic.GroupField<Simplify<ProjectDocumentDataGalleryItem>>;

	/**
	 * Tags field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.tags[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<ProjectDocumentDataTagsItem>>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProjectDocumentData>,
	'project',
	Lang
>;

/**
 * Content for Social media documents
 */
interface SocialMediaDocumentData {
	/**
	 * Social media link field in *Social media*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_media.social_media_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_media_link: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Social media document from Prismic
 *
 * - **API ID**: `social_media`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SocialMediaDocumentData>,
	'social_media',
	Lang
>;

export type AllDocumentTypes =
	| FooterNavigationDocument
	| GeneralSettingsDocument
	| HomepageDocument
	| MainNavigationDocument
	| PageDocument
	| ProjectDocument
	| SocialMediaDocument;

/**
 * Item in *CustomerReviews → Default → Primary → Reviews*
 */
export interface CustomerReviewsSliceDefaultPrimaryReviewsItem {
	/**
	 * avatar field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].avatar
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	avatar: prismic.ImageField<never>;

	/**
	 * name field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;

	/**
	 * date field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;

	/**
	 * rating field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].rating
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	rating: prismic.SelectField<'1' | '2' | '3' | '4' | '5'>;

	/**
	 * content field in *CustomerReviews → Default → Primary → Reviews*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[].content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Primary content in *CustomerReviews → Default → Primary*
 */
export interface CustomerReviewsSliceDefaultPrimary {
	/**
	 * Eyebrow field in *CustomerReviews → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *CustomerReviews → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Reviews field in *CustomerReviews → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: customer_reviews.default.primary.reviews[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	reviews: prismic.GroupField<Simplify<CustomerReviewsSliceDefaultPrimaryReviewsItem>>;
}

/**
 * Default variation for CustomerReviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CustomerReviewsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CustomerReviewsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CustomerReviews*
 */
type CustomerReviewsSliceVariation = CustomerReviewsSliceDefault;

/**
 * CustomerReviews Shared Slice
 *
 * - **API ID**: `customer_reviews`
 * - **Description**: CustomerReviews
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CustomerReviewsSlice = prismic.SharedSlice<
	'customer_reviews',
	CustomerReviewsSliceVariation
>;

/**
 * Item in *Hero → Parallax → Primary → Column 1*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item {}

/**
 * Item in *Hero → Parallax → Primary → Column 2*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item {}

/**
 * Item in *Hero → Parallax → Primary → Column 3*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item {}

/**
 * Primary content in *Hero → Parallax → Primary*
 */
export interface HeroWithNavigationOverlaySliceParallaxPrimary {
	/**
	 * Headline field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;

	/**
	 * Subheadline field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.subheadline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheadline: prismic.RichTextField;

	/**
	 * Call to Action Link field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video URL field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * Column 1 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_1[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_1: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item>>;

	/**
	 * Column 2 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_2[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_2: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item>>;

	/**
	 * Column 3 field in *Hero → Parallax → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.parallax.primary.column_3[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	column_3: prismic.GroupField<Simplify<HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item>>;
}

/**
 * Parallax variation for Hero Slice
 *
 * - **API ID**: `parallax`
 * - **Description**: This variation features the logo top left, navigation top right, headline and description bottom left, and a right-aligned call-to-action link overlayed on an image background.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySliceParallax = prismic.SharedSliceVariation<
	'parallax',
	Simplify<HeroWithNavigationOverlaySliceParallaxPrimary>,
	never
>;

/**
 * Primary content in *Hero → Fullscreen → Primary*
 */
export interface HeroWithNavigationOverlaySliceFullscreenPrimary {
	/**
	 * Headline field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;

	/**
	 * Subheadline field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.subheadline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheadline: prismic.RichTextField;

	/**
	 * Call to Action Link field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video URL field in *Hero → Fullscreen → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_navigation_overlay.fullscreen.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_url: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Fullscreen variation for Hero Slice
 *
 * - **API ID**: `fullscreen`
 * - **Description**: This variation features the logo top left, navigation top right, headline and description bottom left, and a right-aligned call-to-action link overlayed on an image background.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySliceFullscreen = prismic.SharedSliceVariation<
	'fullscreen',
	Simplify<HeroWithNavigationOverlaySliceFullscreenPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroWithNavigationOverlaySliceVariation =
	| HeroWithNavigationOverlaySliceParallax
	| HeroWithNavigationOverlaySliceFullscreen;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_with_navigation_overlay`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavigationOverlaySlice = prismic.SharedSlice<
	'hero_with_navigation_overlay',
	HeroWithNavigationOverlaySliceVariation
>;

/**
 * Item in *ImpactNumbers → Default → Primary → Statistics*
 */
export interface ImpactStatisticsSliceDefaultPrimaryStatsItem {
	/**
	 * Image field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Value field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	value: prismic.KeyTextField;

	/**
	 * Label field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Description field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[].description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;

	/**
	 * Number symbol field in *ImpactNumbers → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: %
	 * - **API ID Path**: impact_statistics.default.primary.stats[].number_symbol
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	number_symbol: prismic.KeyTextField;
}

/**
 * Primary content in *ImpactNumbers → Default → Primary*
 */
export interface ImpactStatisticsSliceDefaultPrimary {
	/**
	 * Light or dark? field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: impact_statistics.default.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: impact_statistics.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * CTA Link field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Statistics field in *ImpactNumbers → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: impact_statistics.default.primary.stats[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	stats: prismic.GroupField<Simplify<ImpactStatisticsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for ImpactNumbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading, introduction text, and a group of statistical blocks, each featuring an image, numeric value, label, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatisticsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImpactStatisticsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ImpactNumbers*
 */
type ImpactStatisticsSliceVariation = ImpactStatisticsSliceDefault;

/**
 * ImpactNumbers Shared Slice
 *
 * - **API ID**: `impact_statistics`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatisticsSlice = prismic.SharedSlice<
	'impact_statistics',
	ImpactStatisticsSliceVariation
>;

/**
 * Item in *LogoGrid → Default Grid → Primary → Logos*
 */
export interface LogoGridSliceDefaultGridPrimaryLogosItem {
	/**
	 * Logo Image field in *LogoGrid → Default Grid → Primary → Logos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_grid.default_grid.primary.logos[].logo_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoGrid → Default Grid → Primary*
 */
export interface LogoGridSliceDefaultGridPrimary {
	/**
	 * Section eyebrow field in *LogoGrid → Default Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Section eyebrow
	 * - **API ID Path**: logo_grid.default_grid.primary.section_eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_eyebrow: prismic.KeyTextField;

	/**
	 * Section title field in *LogoGrid → Default Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Section title
	 * - **API ID Path**: logo_grid.default_grid.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Logos field in *LogoGrid → Default Grid → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_grid.default_grid.primary.logos[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	logos: prismic.GroupField<Simplify<LogoGridSliceDefaultGridPrimaryLogosItem>>;
}

/**
 * Default Grid variation for LogoGrid Slice
 *
 * - **API ID**: `default_grid`
 * - **Description**: A standard grid of logos with support for image- or text-based logos and optional link on each logo.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoGridSliceDefaultGrid = prismic.SharedSliceVariation<
	'default_grid',
	Simplify<LogoGridSliceDefaultGridPrimary>,
	never
>;

/**
 * Slice variation for *LogoGrid*
 */
type LogoGridSliceVariation = LogoGridSliceDefaultGrid;

/**
 * LogoGrid Shared Slice
 *
 * - **API ID**: `logo_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoGridSlice = prismic.SharedSlice<'logo_grid', LogoGridSliceVariation>;

/**
 * Item in *Footer → Default → Primary → Navigation items*
 */
export interface NavigationalMediaGridSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Footer → Default → Primary → Navigation items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[].media
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	media: prismic.ImageField<never>;

	/**
	 * Label field in *Footer → Default → Primary → Navigation items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Destination link field in *Footer → Default → Primary → Navigation items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[].destination
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	destination: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface NavigationalMediaGridSliceDefaultPrimary {
	/**
	 * Navigation items field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigational_media_grid.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<NavigationalMediaGridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard grid navigation with image backgrounds and labels.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationalMediaGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationalMediaGridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Footer*
 */
type NavigationalMediaGridSliceVariation = NavigationalMediaGridSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `navigational_media_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationalMediaGridSlice = prismic.SharedSlice<
	'navigational_media_grid',
	NavigationalMediaGridSliceVariation
>;

/**
 * Item in *HorizontalShowcase → Default → Primary → Projects*
 */
export interface ProjectShowcaseSliceWithFeaturedProjectPrimaryProjectsItem {
	/**
	 * Project field in *HorizontalShowcase → Default → Primary → Projects*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.projects[].project
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project: ContentRelationshipFieldWithData<
		[
			{
				id: 'project';
				fields: ['title', 'location', 'featured_image', { id: 'tags'; fields: ['tag'] }, 'summary'];
			}
		]
	>;
}

/**
 * Primary content in *HorizontalShowcase → Default → Primary*
 */
export interface ProjectShowcaseSliceWithFeaturedProjectPrimary {
	/**
	 * Light or dark? field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: project_showcase.with_featured_project.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * CTA Link field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Projects field in *HorizontalShowcase → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_showcase.with_featured_project.primary.projects[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	projects: prismic.GroupField<
		Simplify<ProjectShowcaseSliceWithFeaturedProjectPrimaryProjectsItem>
	>;
}

/**
 * Default variation for HorizontalShowcase Slice
 *
 * - **API ID**: `with_featured_project`
 * - **Description**: Displays section intro and a primary featured project with category tags and project link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceWithFeaturedProject = prismic.SharedSliceVariation<
	'with_featured_project',
	Simplify<ProjectShowcaseSliceWithFeaturedProjectPrimary>,
	never
>;

/**
 * Slice variation for *HorizontalShowcase*
 */
type ProjectShowcaseSliceVariation = ProjectShowcaseSliceWithFeaturedProject;

/**
 * HorizontalShowcase Shared Slice
 *
 * - **API ID**: `project_showcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSlice = prismic.SharedSlice<
	'project_showcase',
	ProjectShowcaseSliceVariation
>;

/**
 * Item in *ImageText → Image & Text Alternating → Primary → Image & text block*
 */
export interface ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem {
	/**
	 * Image right field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].image_right
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	image_right: prismic.BooleanField;

	/**
	 * Image field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Text field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * CTA button field in *ImageText → Image & Text Alternating → Primary → Image & text block*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[].cta_button
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ImageText → Image & Text Alternating → Primary*
 */
export interface ServiceHighlightsSliceImageTextAlternatingPrimary {
	/**
	 * Light or dark? field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Eyebrow field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Headline field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * CTA Link field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Image & text block field in *ImageText → Image & Text Alternating → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_highlights.image_text_alternating.primary.image_text_block[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	image_text_block: prismic.GroupField<
		Simplify<ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem>
	>;
}

/**
 * Image & Text Alternating variation for ImageText Slice
 *
 * - **API ID**: `image_text_alternating`
 * - **Description**: Displays each service with image and text side by side, alternating image position per item. Supports headline, link to all services, and a repeatable list of service blocks.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightsSliceImageTextAlternating = prismic.SharedSliceVariation<
	'image_text_alternating',
	Simplify<ServiceHighlightsSliceImageTextAlternatingPrimary>,
	never
>;

/**
 * Slice variation for *ImageText*
 */
type ServiceHighlightsSliceVariation = ServiceHighlightsSliceImageTextAlternating;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `service_highlights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightsSlice = prismic.SharedSlice<
	'service_highlights',
	ServiceHighlightsSliceVariation
>;

/**
 * Item in *TeamMembersCarousel → Default → Primary → Team Members*
 */
export interface TeamMembersCarouselSliceDefaultPrimaryTeamMembersItem {
	/**
	 * Photo field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].photo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	photo: prismic.ImageField<never>;

	/**
	 * Name field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;

	/**
	 * Role field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].role
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;

	/**
	 * LinkedIn Link field in *TeamMembersCarousel → Default → Primary → Team Members*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[].social_linkedin
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_linkedin: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *TeamMembersCarousel → Default → Primary*
 */
export interface TeamMembersCarouselSliceDefaultPrimary {
	/**
	 * Light or dark? field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: team_members_carousel.default.primary.dark
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	dark: prismic.BooleanField;

	/**
	 * Section Eyebrow field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: team_members_carousel.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Section Title field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title
	 * - **API ID Path**: team_members_carousel.default.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Section Description field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Description
	 * - **API ID Path**: team_members_carousel.default.primary.section_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_description: prismic.RichTextField;

	/**
	 * CTA Link field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Team Members field in *TeamMembersCarousel → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_members_carousel.default.primary.team_members[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	team_members: prismic.GroupField<Simplify<TeamMembersCarouselSliceDefaultPrimaryTeamMembersItem>>;
}

/**
 * Default variation for TeamMembersCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Carousel layout for showcasing multiple team members, including contact call-to-action and intro heading/description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMembersCarouselSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TeamMembersCarouselSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TeamMembersCarousel*
 */
type TeamMembersCarouselSliceVariation = TeamMembersCarouselSliceDefault;

/**
 * TeamMembersCarousel Shared Slice
 *
 * - **API ID**: `team_members_carousel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMembersCarouselSlice = prismic.SharedSlice<
	'team_members_carousel',
	TeamMembersCarouselSliceVariation
>;

/**
 * Primary content in *VideoBannerSection → Default → Primary*
 */
export interface VideoBannerSectionSliceDefaultPrimary {
	/**
	 * Headline field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Content field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * CTA link field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Video field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * Poster image field in *VideoBannerSection → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_banner_section.default.primary.poster_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	poster_image: prismic.ImageField<never>;
}

/**
 * Default variation for VideoBannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoBannerSectionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoBannerSectionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VideoBannerSection*
 */
type VideoBannerSectionSliceVariation = VideoBannerSectionSliceDefault;

/**
 * VideoBannerSection Shared Slice
 *
 * - **API ID**: `video_banner_section`
 * - **Description**: VideoBannerSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoBannerSectionSlice = prismic.SharedSlice<
	'video_banner_section',
	VideoBannerSectionSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterNavigationDocument,
			FooterNavigationDocumentData,
			GeneralSettingsDocument,
			GeneralSettingsDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			MainNavigationDocument,
			MainNavigationDocumentData,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataGalleryItem,
			ProjectDocumentDataTagsItem,
			SocialMediaDocument,
			SocialMediaDocumentData,
			AllDocumentTypes,
			CustomerReviewsSlice,
			CustomerReviewsSliceDefaultPrimaryReviewsItem,
			CustomerReviewsSliceDefaultPrimary,
			CustomerReviewsSliceVariation,
			CustomerReviewsSliceDefault,
			HeroWithNavigationOverlaySlice,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn1Item,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn2Item,
			HeroWithNavigationOverlaySliceParallaxPrimaryColumn3Item,
			HeroWithNavigationOverlaySliceParallaxPrimary,
			HeroWithNavigationOverlaySliceFullscreenPrimary,
			HeroWithNavigationOverlaySliceVariation,
			HeroWithNavigationOverlaySliceParallax,
			HeroWithNavigationOverlaySliceFullscreen,
			ImpactStatisticsSlice,
			ImpactStatisticsSliceDefaultPrimaryStatsItem,
			ImpactStatisticsSliceDefaultPrimary,
			ImpactStatisticsSliceVariation,
			ImpactStatisticsSliceDefault,
			LogoGridSlice,
			LogoGridSliceDefaultGridPrimaryLogosItem,
			LogoGridSliceDefaultGridPrimary,
			LogoGridSliceVariation,
			LogoGridSliceDefaultGrid,
			NavigationalMediaGridSlice,
			NavigationalMediaGridSliceDefaultPrimaryItemsItem,
			NavigationalMediaGridSliceDefaultPrimary,
			NavigationalMediaGridSliceVariation,
			NavigationalMediaGridSliceDefault,
			ProjectShowcaseSlice,
			ProjectShowcaseSliceWithFeaturedProjectPrimaryProjectsItem,
			ProjectShowcaseSliceWithFeaturedProjectPrimary,
			ProjectShowcaseSliceVariation,
			ProjectShowcaseSliceWithFeaturedProject,
			ServiceHighlightsSlice,
			ServiceHighlightsSliceImageTextAlternatingPrimaryImageTextBlockItem,
			ServiceHighlightsSliceImageTextAlternatingPrimary,
			ServiceHighlightsSliceVariation,
			ServiceHighlightsSliceImageTextAlternating,
			TeamMembersCarouselSlice,
			TeamMembersCarouselSliceDefaultPrimaryTeamMembersItem,
			TeamMembersCarouselSliceDefaultPrimary,
			TeamMembersCarouselSliceVariation,
			TeamMembersCarouselSliceDefault,
			VideoBannerSectionSlice,
			VideoBannerSectionSliceDefaultPrimary,
			VideoBannerSectionSliceVariation,
			VideoBannerSectionSliceDefault
		};
	}
}
